from kafka import KafkaConsumer
import traceback

try:
    consumer = KafkaConsumer(
        'mytopic',
        bootstrap_servers=['localhost:9092'],
        group_id='my-group',
    )

    for message in consumer:
        print(message)
        
except Exception as e:
    print("Exception occurred: ", str(e))
    print("Traceback: ", traceback.format_exc())
